development:
  adapter: mysql2
  encoding: utf8
  database: meetcha_halfway_dev
  username: 
  password: 
  host: localhost
  pool: 5

test:
  adapter: mysql2
  encoding: utf8
  database: meetcha_halfway_test
  username: 
  password: 
  host: localhost
  pool: 5

production:
  adapter: mysql2
  encoding: utf8
  database: meetcha_halfway_prod
  username: 
  password: 
  host: localhost
  pool: 5
