# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 004ef0db5a1bb69044449f8464d082fab11e4ef2a2826a3fcab321d7087b39bcf6d0e43dbf762c9e3a892a40ac26e6daf90253be5737193c1dae4be5da08d4c9

test:
  secret_key_base: 309dcb14e5b95afcb8c87b2cc677f1941da24ec33c4b26b2b1c84204ac3133d74015d5eeb5e1559950b878b7292a8581bdfe21fabb36e9bec8aebd74fe21c41b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
